version: 2.1
orbs:
  node: circleci/node@5
  aws-s3: circleci/aws-s3@3.1.1
  # aws-s3: circleci/aws-s3@4.0.0 # use the AWS S3 orb in your configuration
  # aws-cli: circleci/aws-cli@4.1.3

jobs:
  checkout_and_install:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
            
  build-node:
    # Build node project
    executor: node/default
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Vite build
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true | ls -al | find .
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .

  deploy:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/base:stable
       
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project
      - run:
          name: List Directory
          command: ls -al
      # - run:
      #     name: Configure AWS CLI
          # command: |
          #   echo "[default]" > ~/.aws/credentials
          #   echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          #   echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          #   aws configure set region us-east-1
    
      - aws-s3/sync:
          from: dist
          to: 's3://circle-ci-aman'

workflows:
  test_and_build:
    jobs:
      - checkout_and_install
      - build-node:
          requires:
            - checkout_and_install
      - deploy:
          requires:
            - build-node # Only run deploy job once the build job has completed
          filters:
            branches:
              only: main # Only deploy when the commit is on the Main branch
